name: Deploy to firebase

on: [workflow_dispatch, push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: install
        run: yarn install
      - name: build & export
        run: yarn export
      - name: deploy
        run: yarn deploy:token
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: after-deploy
        run: yarn after-deploy
        env:
          API_KEY: ${{secrets.API_KEY}}
