name: Deploy to firebase

on: [workflow_dispatch, push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: install
        run: yarn install
      - name: enable web frameworks
        run: yarn enableWebFrameworks
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GH_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: yuda-fox-dev
      - name: after-deploy
        run: yarn after-deploy
        env:
          API_KEY: ${{secrets.API_KEY}}
